### ISSUE TITLE
USCS tools need to be an older version

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/genomics-VM#20]
We had problems installing the latest version of faToTwoBit and wigToBigWig. An older version worked. (probably because we are using CentOS6). We'll need to update the vagrantfile accordingly. Strategy: instead of pulling the latest version of the tools, grab an older version and 
 have vagrant compile it. E.g. http://hgdownload.soe.ucsc.edu/admin/exe/userApps.archive/userApps.v326.src.tgz

**Comment by childers** [comment]
The kenttools branch downloads and builds successfully, We'll need to test it on another machine.
